### ISSUE TITLE
1.21 support?

### ISSUE THREAD

**Issue by scarywoods** [xNasuni/PlayerVisibility#2]
Title is pretty self explanatory.

**Comment by xNasuni** [comment]
i'll try to be as quick as possible.

expect an update before august.

**Comment by xNasuni** [comment]
okay
https://modrinth.com/mod/player-visibility/version/gsKIrrjp
https://github.com/xNasuni/PlayerVisibility/releases/tag/1.0+1.21

let me know if you have any issues, i tested it with & without other mods and it seemed to work
